spring:
  application:
    name: 10-Bank-RestApi
    
  datasource:
    url: jdbc:mysql://localhost:3306/mannu_2912
    username: root
    password: 1995
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
      
      
server:
  port: 9099